const URLS = {
  intensive: 'https://forms.yandex.ru/u/6abfa1a884227c8d53a4ab7e',
  sintez: 'https://api.sintez.space/register?ref=derevopark',
  web: 'https://ai-leto-26-nisha.vercel.app/#slide-01',
  gameWeb: 'https://nakarandashe27.github.io/PROrestavrazia-mini-game/',
  gameTG: 'https://t.me/prorestavraziagame_bot?startapp',
  logoSPB: 'https://nakarandashe27.github.io/3D-LOGO-SPBGASU/',
  logoArt: 'https://nakarandashe27.github.io/3D-LOGO-ARTBRODSKY/#logo=round',
};
const MEDIA = {
  sintez: 'SINTEZ/guide_1080p.mp4',
  gh: 'Script Grasshopper Natalia/Скрипт для подсчета ГНС/Скрипт для подсчета ГНС.mp4',
  rhino: 'Rhino MCP/БЦ СЕНАТОР кейс.mp4',
  revit: 'REVIT MCP/final_v3.mp4',
  rhighai: 'RhiGhAI plugin/manege-rhighai-presentation.mp4',
  villa: 'villa savoye/villa-savoye-16x9-v3.mp4',
  game: 'PROrest GAME/prorestavraciya-96s.mp4',
  artmap: 'artmap screencast/brag.mp4',
};
const arrow = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
const link = (href, text, className='pill') => `<a class="${className}" href="${href}" target="_blank" rel="noopener noreferrer">${text}${arrow}</a>`;
const qrCard = (src, href, title, caption) => `<a class="qr-card" href="${href}" target="_blank" rel="noopener noreferrer"><img src="assets/qr/${src}" alt="QR: ${title}"><h3>${title}</h3><p>${caption}</p><span class="inline-link">Открыть ссылку ${arrow}</span></a>`;
const video = (id, title, caption, notes, block, speaker='Ярослав') => ({type:'video', title, block, speaker, caption, media:id, notes});
const chapter = (block, title, subtitle, speaker) => ({type:'chapter', block, title, subtitle, speaker, notes:'Обложка раздела. Формулировка заголовка — редакторский вариант для черновика.'});
const placeholder = (block,title,subtitle,speaker,notes) => ({type:'placeholder', block,title,subtitle,speaker,notes,status:'Материал ожидается'});

const SLIDES = [
  {type:'cover',block:'01 / Начало',title:'ИИ, сделай красиво',speaker:'Ярослав + Наталия',html:`<div class="cover-inner"><svg class="mark grad cover-mark" viewBox="0 0 75 75" aria-hidden="true"><path d="M0 18.75C0 8.39 8.39 0 18.75 0H56.25V18.75H0Z"/><path class="fold" d="M56.25 0 75 18.75H56.25Z"/><path d="M56.25 18.75H75V56.25C75 66.61 66.61 75 56.25 75Z"/><path d="M0 53.12C0 41.04 9.79 31.25 21.88 31.25 33.96 31.25 43.75 41.04 43.75 53.12V75H21.88C9.79 75 0 65.21 0 53.12Z"/></svg><p class="cover-event">ЛЕКТОРИЙ / АРХНЕДЕЛЯ</p><h1>ИИ, СДЕЛАЙ<br>КРАСИВО</h1><p class="cover-subtitle">Новые инструменты в руках архитектора</p><div class="cover-speakers"><span>Ярослав Уваровский</span><span>Наталия Саркисова</span></div><button class="pill light" data-next>Начнём с вашей практики ${arrow}</button></div><div class="cover-meta"><span>05.10 / 18:30</span><span>СПбГАСУ / 632А</span></div>`,notes:'Тема, спикеры, дата и место подтверждены. Подзаголовок и обложка — предложение для черновика. PDF использован как визуальный ориентир, а не источник программы и дат интенсива.'},
  {type:'content',block:'01 / Начало',title:'Спикеры',speaker:'Ярослав + Наталия',html:`<div class="speakers-map">
<svg class="sp-lines" viewBox="0 0 100 56.25" aria-hidden="true"><path pathLength="1" d="M11.8 11.6V17.4M11.8 24.6V35.4"/><path pathLength="1" d="M18.8 21H21.5M55.5 21H86.3Q88.3 21 88.3 23V29.5"/><path pathLength="1" d="M18.8 39H21.5M55.5 39H63"/></svg>
<span class="sp-pill">Спикеры</span><span class="sp-arrows sp-down">↓<br>↓<br>↓</span>
<div class="sp-name sp-y">Ярослав<br>Уваровский</div>
<div class="sp-desc sp-y"><p><b>Архитектор, руководитель AI-направления ландшафтного бюро DEREVO PARK</b></p><p>Преподаватель школы Арт.Бродский по нейросетям</p><p>Автор Telegram-канала «nakarandashé» про ИИ для архитектора</p><p>Студент магистратуры СПбГАСУ, профиль «Дизайн архитектурной среды»</p></div>
<span class="sp-arrows sp-y">→ → →</span>
<div class="sp-name sp-n">Наталия<br>Саркисова</div>
<div class="sp-desc sp-n"><p><b>Практикующий архитектор в бюро IND</b></p><p>Ранее работала в бюро Semren Mansson, стажировалась в «T+T Architects», «Tobe Architects» и Лаборатории «МЛА+»</p><p>Студент магистратуры «Урбанистика» в ИТМО</p></div>
<span class="sp-arrows sp-n">→ →</span>
<figure class="sp-photo sp-n"><img src="assets/speakers/natalia.jpg" alt="Наталия Саркисова"></figure>
<figure class="sp-photo sp-y"><img src="assets/speakers/yaroslav.jpg" alt="Ярослав Уваровский"></figure>
</div>`,notes:'Схема спикеров по референсу автора (05.10). Биографии и фотографии переданы автором; формулировки биографии Наталии разбиты на строки без изменения фактов.'},
  {type:'poll',block:'01 / Начало',title:'Что мешает использовать ИИ?',speaker:'Ярослав + Наталия',html:`<div class="poll-layout"><div><p class="section-label">Разговор с залом</p><h2>ЧТО ВАС<br>ОСТАНАВЛИВАЕТ?</h2><p class="body-text">Что мешает применять ИИ<br>в работе или учёбе?</p><p class="small-note">Выберите вариант — обсудим его.</p></div><div class="poll-options">${['Не понимаю, с какой задачи начать','Трудно управлять результатом','Привычным способом быстрее','Доступ, стоимость или настройка','Ничего — уже использую'].map((s,i)=>`<button data-answer="${i}" aria-pressed="false"><span>0${i+1}</span>${s}${arrow}</button>`).join('')}<p id="poll-feedback" class="poll-feedback" aria-live="polite"></p><small>В черновике выбор сохраняется только на этом устройстве.</small></div></div>`,notes:'Тема барьеров подтверждена, точные варианты — редакторское предложение. Здесь локальная демонстрация выбора, без сбора голосов аудитории. На лекции допустим ответ поднятием рук. Сессия для телефонов пока не реализована.'},
  {type:'statement',block:'01 / Начало',title:'Задачу ставит архитектор',speaker:'Ярослав + Наталия',html:`<div class="statement-inner"><h2>ЗАДАЧУ СТАВИТ<br>АРХИТЕКТОР.</h2><p>Выбор инструмента, отбор и проверка результата<br>остаются частью нашей работы.</p><div class="statement-rule">Иногда привычный способ проще и быстрее.</div></div>`,notes:'Подтверждённый смысл лекции. Живая подводка: ожидания от «сделай красиво», пробы, исправления и опыт. Короткая историческая аналогия остаётся возможной репликой; самостоятельный слайд с историческими утверждениями пока не создан.'},
  {type:'content',block:'01 / Начало',title:'С чего выбирать инструмент',speaker:'Ярослав + Наталия',html:`<h2 class="center-title">НАЧНИТЕ С ЗАДАЧИ</h2><div class="task-grid">${[['01','Информация','Найти, разобрать, сопоставить.'],['02','Изображения','Разработать визуальное решение.'],['03','Геометрия','Построить и проверить в рабочем софте.'],['04','Свои инструменты','Автоматизировать и придумать новый формат.']].map(x=>`<div><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div><p class="bottom-thought">Какой результат нужен? Чем управлять? Как проверить?</p>`,notes:'Редакторская карта задач, согласующаяся с выбранными кейсами. Не обещает универсальность или автоматическое проектирование.'},
  chapter('02 / Визуализация','КРАСИВО.<br>ПО ВАШИМ ПРАВИЛАМ.','Контролируемая визуализация / SINTEZ + ComfyUI','Ярослав + Наталия'),
  video('sintez','SINTEZ В PHOTOSHOP','Генерация и редактирование в привычном инструменте · 2:33','Подтверждены видео на отдельном слайде и следующий слайд с реферальной ссылкой. Не обещать бонусы или скидки.', '02 / Визуализация'),
  {type:'content',block:'02 / Визуализация',title:'Попробовать SINTEZ',speaker:'Ярослав',html:`<div class="qr-layout"><div><p class="section-label">SINTEZ / Photoshop</p><h2>ПОПРОБУЙТЕ<br>НА СВОЕЙ<br>ЗАДАЧЕ.</h2><p class="body-text">Генерация и редактирование изображений с помощью ИИ прямо в Photoshop.</p><div class="promo"><span class="promo-label">Промокод · только сегодня</span><button class="promo-code" data-copy="NAKARANDASHE15" aria-label="Скопировать промокод NAKARANDASHE15"><span>NAKARANDASHE15</span><em>Скопировать</em></button><p class="promo-terms">Пополните счёт на любую сумму не меньше минимальной — после оплаты на счёт придёт <b>+15%</b>.</p><p class="promo-timer" data-deadline="2026-10-05T23:59:59+03:00">До полуночи 5 октября — кто успеет, тот успеет</p></div></div>${qrCard('sintez.svg',URLS.sintez,'Начать работу в SINTEZ','Регистрация в SINTEZ')}</div>`,notes:'Промокод NAKARANDASHE15 (передан автором 05.10): +15% к пополнению на любую сумму не меньше минимальной, действует только 5 октября до полуночи. Код derevopark со слайда убран; QR и ссылка по-прежнему ведут на https://api.sintez.space/register?ref=derevopark.'},
  video('comfyui','COMFYUI / АПСКЕЙЛ ВИЗУАЛИЗАЦИИ','Workflow апскейла в ComfyUI · 0:41','Ролик передан 05.10 (исходник ComfyUI/IMG_4989.MOV, перекодирован в H.264; заставка CapCut в конце обрезана). По кадрам — апскейл визуализации жилого квартала. Не обещать передачу workflow или модели. В ролике есть звук.','02 / Визуализация','Наталия'),
  chapter('03 / Свой инструмент','ПОД СВОЮ<br>ЗАДАЧУ.','Создание скрипта с помощью ИИ / Grasshopper','Наталия'),
  {type:'content',block:'03 / Свой инструмент',title:'IND / Параметрическая основа',speaker:'Наталия',html:`<div class="ind-layout"><div class="ind-text"><p class="section-label">Кейс бюро IND · Николай Фанеев, Пётр Клименко</p><h2>ПАРАМЕТРИЧЕСКАЯ<br>ОСНОВА</h2><p class="body-text">Вместо ручной сборки одного варианта создаётся система параметров, позволяющая быстро проверять разные состояния формы.</p></div><div class="ind-bento"><img class="ind-big" src="assets/ind/render.jpg" alt="Визуализация здания, IND"><img src="assets/ind/graph.jpg" alt="Граф Grasshopper"><img src="assets/ind/model.jpg" alt="Каркасная модель фасада"></div></div>`,notes:'Материал из презентации IND «Фанеев × Клименко, ИИ лето» (стр. 5–6), передан автором 05.10. Текст подписи — со страницы 5 презентации IND. Ведёт Наталия.'},
  {type:'content',block:'03 / Свой инструмент',title:'IND / Визуальные пробы',speaker:'Наталия',html:`<div class="ind-probes-layout"><div class="ind-text"><p class="section-label">Кейс бюро IND</p><h2>ВИЗУАЛЬНЫЕ<br>ПРОБЫ</h2></div><div class="ind-flow"><div class="ind-probes">${[1,2,3,4,5,6].map(n=>`<img src="assets/ind/probe${n}.jpg" alt="Проба ${n}">`).join('')}</div><span class="ind-arrow">→ → →</span><img class="ind-final" src="assets/ind/final.jpg" alt="Выбранный вариант башни"></div></div><div class="ind-bottom"><blockquote class="ind-quote"><p><b>Нейросеть — не замена архитектору:</b> это новый рабочий слой профессии, позволяющий расширить возможности, сохраняя контроль</p><cite>IND · Николай Фанеев, Пётр Клименко</cite></blockquote><a class="mini-qr" href="https://t.me/indstudio" target="_blank" rel="noopener noreferrer"><img src="assets/qr/ind.png" alt="QR: Telegram-канал IND"><span><b>IND</b>t.me/indstudio</span></a></div>`,notes:'Стр. 11 и 18 презентации IND: пробы → выбранный вариант; цитата IND. Маленький QR ведёт на Telegram-канал IND (t.me/indstudio, адрес взят со страницы QR в той же презентации).'},
  video('gh','РАСЧЁТ ГНС В GRASSHOPPER','Массинг → параметры → отчёт · 1:31','Наталия создала скрипт с помощью ИИ; обычный расчёт без нейросети. Массинг строит человек. ГНС сохраняем без самостоятельной расшифровки. Видео содержит звук, отдельный MP3 не подключаем одновременно. Формулы и единицы отдельно не проверены.','03 / Свой инструмент','Наталия'),
  chapter('04 / Профессиональный софт','ИИ ВНУТРИ<br>ПРИВЫЧНОГО СОФТА.','Claude и GPT-6 Astra через MCP → Rhino / Grasshopper / Revit + плагин RhiGhAI','Наталия + Ярослав'),
  video('ind','CLAUDE → MCP → GRASSHOPPER','Кейс IND · Claude Fable 5 собирает definition башни с нуля по ТЗ · 0:40','Ролик передан автором 05.10 (кейс IND/Result.mp4, 4K → 1080p, без звука). По кадрам: Claude Fable 5 (режим Cowork) через Rhino MCP Platform собирает Grasshopper-definition башни с нуля по ТЗ и сам проверяет критерии приёмки. Запись сделана на компьютере IND. Ведёт Наталия; рассказ о связке с Claude — до GPT-6 Astra.','04 / Профессиональный софт','Наталия'),
  video('rhino','GPT-6 ASTRA → MCP → RHINO','БЦ «Сенатор» · xhigh · ускоренная запись · 1:12','По автору, качество и проработка впечатлили, лимитов потрачено меньше, чем ожидал. Это личный опыт без числового обещания. Не упоминать RED7 и Blender. Соотношение видео 16:10, весь кадр сохраняется. Один слайд — редакторский выбор для этого черновика.','04 / Профессиональный софт'),
  video('revit','GPT-6 ASTRA → MCP → REVIT','Троицкий-Измайловский собор · модель строится по одной команде · 1:31','Ролик передан автором 05.10. Объект — Троицкий-Измайловский собор; связка Codex GPT-6 Astra → Revit MCP → Revit API, подписи взяты из самой записи. Числа в ролике (главы, колонны, звёзды, проверки) относятся к этой модели, не общее обещание. На созвоне Ярослав отмечал трудности с точностью размеров в пробах: не обещать точную модель по любому запросу. В ролике есть звук.','04 / Профессиональный софт'),
  video('rhighai','RHIGHAI / МОЙ ПЛАГИН ДЛЯ RHINO','Модель ЦВЗ «Манеж» · запрос → геометрия и граф Grasshopper · 1:00','Один видеослайд подтверждён. RhiGhAI отдельно от MCP. В ролике Codex GPT-6.1 Sol. Цифры в записи относятся к конкретному кейсу, не общему обещанию скорости. Положение после Revit — редакторский вариант: точный слот ещё открыт.','04 / Профессиональный софт'),
  chapter('05 / Расширение практики','АРХИТЕКТУРА<br>СТАНОВИТСЯ ШИРЕ.','Видео, веб-презентации, игры, продукты и интерактивные объекты','Ярослав'),
  video('villa','VILLA SAVOYE','Сценарий автора + DWG-модель + Opus 5.5 → видео · 0:32','Первый кейс расширения практики. Автор задал логику и сценарий, передал DWG. IFC назван альтернативой, не использованным форматом. Среда и рендер не названы; не приписывать Three.js или Remotion.','05 / Расширение практики'),
  {type:'web',block:'05 / Расширение практики',title:'Презентация как веб-страница',speaker:'Ярослав',url:URLS.web,html:`<div class="web-intro"><p class="section-label">Сама эта лекция — пример такого формата</p><h2>ПРЕЗЕНТАЦИЯ<br>ПО ССЫЛКЕ.</h2><p>На компьютере. На телефоне.<br>С видео и взаимодействиями.</p><p class="small-note">Мобильную вёрстку нужно адаптировать.<br>В выбранном примере интерактивов немного.</p>${link(URLS.web,'Открыть пример')}</div><div class="embed-wrap web-preview"><div class="web-paper"><span>HTML / WEB</span><h3>Архитектор,<br>который перестал<br>ждать нужный софт</h3><button class="pill" data-load-embed>Показать пример ${arrow}</button></div></div>`,notes:'Выбранный URL сохранён с #slide-01. Тексты описывают формат, не приписывают этому примеру квизы или 3D. Сначала показана обложка-ссылка; кнопка загружает внешнюю презентацию в iframe. Если встраивание недоступно, есть прямая ссылка.'},
  video('game','ИГРА «ПРО РЕСТАВРАЦИЮ»','Архитектурная тема в игровом формате · участие СПбГАСУ · 1:36','Видео → отдельный слайд с двумя QR. Числа в ролике описывают устройство игры, не посещаемость. Инструменты разработки и точный вклад ИИ пока не переданы.','05 / Расширение практики'),
  {type:'content',block:'05 / Расширение практики',title:'Попробовать игру',speaker:'Ярослав',html:`<h2 class="center-title">ТЕПЕРЬ ВАША ОЧЕРЕДЬ</h2><div class="qr-pair">${qrCard('game-web.svg',URLS.gameWeb,'В браузере','Веб-версия для компьютера')}${qrCard('game-telegram.svg',URLS.gameTG,'В Telegram','Открыть игру как Mini App')}</div>`,notes:'Обе ссылки кликабельны; Telegram URL сохраняет ?startapp. Прохождение игры в черновике не требуется.'},
  video('artmap','КАРТА АРХИТЕКТУРНЫХ ВУЗОВ РФ','Арт.Бродский Старт · от идеи к собственному продукту · 0:48','По автору, ИИ упростил создание продукта, который на серьёзном этапе реализации. Публичная ссылка не передана; QR не добавлять. Не заявлять готовый публичный запуск или точное число вузов.','05 / Расширение практики'),
  {type:'embed',block:'05 / Расширение практики',title:'СПбГАСУ / 3D-логотип',speaker:'Ярослав',url:URLS.logoSPB,notes:'Предпоследний слайд раздела расширения практики. Живой объект: вращение, настройки и экспорт во внешнем приложении. Кнопка загрузки подключает iframe, внешняя ссылка сохранена. Самостоятельная игра на телефоне после лекции; рабочая аудитория здесь не синхронизируется.'},
  {type:'embed',block:'05 / Расширение практики',title:'Арт.Бродский / 3D-логотип',speaker:'Ярослав',url:URLS.logoArt,notes:'Последний слайд раздела, не всей лекции. URL сохраняет #logo=round. После логотипа идут финал, вопросы, каналы, интенсив.'},
  {type:'content',block:'06 / Завершение',title:'Ваш первый эксперимент',speaker:'Ярослав + Наталия',html:`<div class="closing-layout"><h2>ЧТО ПОПРОБУЕТЕ<br>ПЕРВЫМ?</h2><div class="closing-steps"><div><span>01</span><p>Возьмите небольшую<br>реальную задачу.</p></div><div><span>02</span><p>Сравните результат<br>с привычным способом.</p></div><div><span>03</span><p>Сохраните удачный приём.<br>Продолжайте экспериментировать.</p></div></div><p class="bottom-thought">Опыт выбора инструмента появляется в практике.</p></div>`,notes:'Текст финального призыва — предложение на основе подтверждённой цели. Не гарантирует окупаемость любой пробы или карьерный успех.'},
  {type:'statement',block:'06 / Завершение',title:'Ваши вопросы',speaker:'Ярослав + Наталия',html:`<div class="statement-inner"><h2>ВАШИ<br>ВОПРОСЫ.</h2><p>Что захотелось попробовать?<br>Что осталось непонятным?</p><div class="statement-rule">Поговорим о ваших задачах.</div></div>`,notes:'Положение вопросов здесь — редакторский вариант. Порядок вопросов, подарков и розыгрыша ещё обсуждается. Бот, призы и правила не переданы; фиктивный QR или автоматический розыгрыш не создаём.'},
  {type:'content',block:'06 / Завершение',title:'Продолжим разговор',speaker:'Ярослав + Наталия',html:`<h2 class="center-title">ОСТАЁМСЯ НА СВЯЗИ</h2><div class="channel-grid">${qrCard('yaroslav.png','https://t.me/na_karandashe27','Ярослав Уваровский','Тесты, наблюдения и инструменты')}${qrCard('natalia.png','https://t.me/postcardby','Наталия Саркисова','Канал Наталии')}${qrCard('school.png','https://t.me/artbrodsky','Арт.Бродский','Канал школы')}</div>`,notes:'Канал Наталии передан автором напрямую. Адреса Ярослава и школы взяты из ранее переданных материалов. QR создаются на эти точные ссылки. Порядок трёх карточек — редакторский вариант.'},
  {type:'cover',block:'06 / Завершение',title:'Интенсив Rhino + Grasshopper',speaker:'Ярослав + Наталия',html:`<div class="cover-inner finale intensive-layout"><div class="intensive-copy"><p class="cover-event">ПРОДОЛЖИМ НА ИНТЕНСИВЕ АРТ.БРОДСКИЙ</p><h2>RHINO +<br>GRASSHOPPER</h2><p class="cover-subtitle">От первых проб — к работе со своими задачами</p>${link(URLS.intensive,'Записаться на интенсив','pill light')}</div><a class="intensive-qr" href="${URLS.intensive}" target="_blank" rel="noopener noreferrer"><img src="assets/qr/intensive.png" alt="QR-код формы записи на интенсив Rhino + Grasshopper"><strong>Запись на интенсив</strong><span>Наведите камеру телефона</span></a></div>`,notes:'Форма записи передана автором 05.10.2026: https://forms.yandex.ru/u/6abfa1a884227c8d53a4ab7e. QR и кнопка ведут на этот точный адрес. Точные программа, дата старта и цена пока не переданы. Старые даты и обещания из стилевого PDF не переносим. Финальная формулировка — предложение.'},
];
